/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AusstattungRouteImport } from './routes/ausstattung'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as PlanerRouteImport } from './routes/planer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AusstattungRoute = AusstattungRouteImport.update({
  id: '/ausstattung',
  path: '/ausstattung',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanerRoute = PlanerRouteImport.update({
  id: '/planer',
  path: '/planer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ausstattung': typeof AusstattungRoute
  '/faq': typeof FaqRoute
  '/kontakt': typeof KontaktRoute
  '/planer': typeof PlanerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ausstattung': typeof AusstattungRoute
  '/faq': typeof FaqRoute
  '/kontakt': typeof KontaktRoute
  '/planer': typeof PlanerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ausstattung': typeof AusstattungRoute
  '/faq': typeof FaqRoute
  '/kontakt': typeof KontaktRoute
  '/planer': typeof PlanerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ausstattung' | '/faq' | '/kontakt' | '/planer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ausstattung' | '/faq' | '/kontakt' | '/planer'
  id: '__root__' | '/' | '/ausstattung' | '/faq' | '/kontakt' | '/planer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AusstattungRoute: typeof AusstattungRoute
  FaqRoute: typeof FaqRoute
  KontaktRoute: typeof KontaktRoute
  PlanerRoute: typeof PlanerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ausstattung': {
      id: '/ausstattung'
      path: '/ausstattung'
      fullPath: '/ausstattung'
      preLoaderRoute: typeof AusstattungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planer': {
      id: '/planer'
      path: '/planer'
      fullPath: '/planer'
      preLoaderRoute: typeof PlanerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AusstattungRoute: AusstattungRoute,
  FaqRoute: FaqRoute,
  KontaktRoute: KontaktRoute,
  PlanerRoute: PlanerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}